### ISSUE TITLE
Get user and users back-end routes

### ISSUE THREAD

**Issue by skassam21** [hatchways/team-pretzel#20]
- Get user (/users/:user_id) - Sunny
   - Public
   - Return the user object, as well as their polls and friend lists 
- Get users - Sunny
   - Return all users on the platform (name, profile pic, and id)
   - Create a script to seed a bunch of user profiles

**Comment by m3tron** [comment]
needs users.findAll()

**Comment by k-awe-some** [comment]
> needs users.findAll()

@m3tron I'll tackle that as well if you want

**Comment by m3tron** [comment]
> > needs users.findAll()
> 
> @m3tron I'll tackle that as well if you want

sounds good
